### ISSUE TITLE
Possible to capture page outside of browser window bounds ?

### ISSUE THREAD

**Issue by odelaere** [datakurre/robotframework-selenium2screenshots#7]
I need to capture an entire formular which overflows the browser window. 

Whenever I try, The result picture doesn't show the overflowing content. Only a transparent (on Firefox) or a black (on Chrome) frame instead

I am using Firefox 49.0, Google Chrome 54.0.2840.71 (64-bit) and those dependencies :
plone.app.robotframework = 1.0.1
robotframework = 3.0
robotframework-debuglibrary = 0.8
robotframework-selenium2library = 1.8.0
robotframework-selenium2screenshots = 0.7.2
robotsuite = 1.7.0
selenium = 3.0.1
sphinxcontrib-robotframework = 0.6.1

I could make such screen capture withe older versions of libraries and browser but it is not possible anymore.

Is it possible to add this feature in the new versions ?

![sample on firefox](https://cloud.githubusercontent.com/assets/23073839/19770804/f7f27998-9c60-11e6-8543-740bc34e67b5.png)
![sample on chrome](https://cloud.githubusercontent.com/assets/23073839/19770826/096ac360-9c61-11e6-8dcc-61fa38499108.png)

**Comment by HelioGuilherme66** [comment]
Have you tried PhantomJS (pseudo-browser)? A long time ago I managed to get full screenshots of long pages.

**Comment by odelaere** [comment]
I tried with PhantomJS but didn't get a better result ;)

**Comment by datakurre** [comment]
@odelaere Probably your best hope is PhantomJS and very tall window with Set window size -keyword. Or find out working old versions (Selenium 2.x) and use PhantomJS (the latest Firefox requires the latest Selenium).

According to Selenium Webdriver spec, the screenshot command should only include viewport
https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot

Selenium has previously taken full page screenshots on some browsers, but if that's not the case anymore, maybe they have fixed it to comply with the specification (in Selenium 3.x).

This is unfortunate, and nothing that could be fixed in this library (quite the opposite: because of the full page screenshots, this library included screenshot for capturing only the current viewport, which seems to be obsolete now).
